#!/usr/bin/env bash
# a script that uses task 0 to make a short and sweet script
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
