#!/usr/bin/env bash
# must be running as nginx user and listen on all active IPs
# a script that configures the container to fit the requirements
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
